language: python
python:
  - "3.5"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - pytest
after_success:
  - coveralls
deploy:
  provider: heroku
  api_key: 
  secure: "572f6992-df23-40ec-a63f-9389fcee5fdf"