language: python
python:
  - "3.5"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
script:
  - py.test tests/test_api.py
  - pytest --cov app
after_success:
  - coveralls